namespace DAL.Emails {

    public class IdentificacaoMensagemEmailConst {
        
        public static readonly string PROCESSO_TITULACAO_CONVITE_AVALIADOR = "PROCESSO_TITULACAO_CONVITE_AVALIADOR";
        public static readonly string PROCESSO_TITULACAO_NOVA_INSCRICAO = "PROCESSO_TITULACAO_NOVA_INSCRICAO";
        public static readonly string PROCESSO_TITULACAO_CONFIRMACAO_PAGAMENTO = "PROCESSO_TITULACAO_CONFIRMACAO_PAGAMENTO";
        public static readonly string PROCESSO_TITULACAO_COBRANCA = "PROCESSO_TITULACAO_COBRANCA";
        public static readonly string PROCESSO_TITULACAO_DOCUMENTO_APROVACAO = "PROCESSO_TITULACAO_DOCUMENTO_APROVACAO";
        public static readonly string PROCESSO_TITULACAO_DOCUMENTO_PENDENCIA = "PROCESSO_TITULACAO_DOCUMENTO_PENDENCIA";
        public static readonly string PROCESSO_TITULACAO_DOCUMENTO_REPROVACAO = "PROCESSO_TITULACAO_DOCUMENTO_REPROVACAO";
        public static readonly string PROCESSO_TITULACAO_ANALISE_CURRICULO = "PROCESSO_TITULACAO_ANALISE_CURRICULO";
        public static readonly string PROCESSO_TITULACAO_ENVIO_DOCUMENTOS = "PROCESSO_TITULACAO_ENVIO_DOCUMENTOS";
        public static readonly string PROCESSO_TITULACAO_ANALISE_INSCRICAO = "PROCESSO_TITULACAO_ANALISE_INSCRICAO";
        public static readonly string PROCESSO_TITULACAO_ANALISE_CURRICULO_FINALIZADA =  "PROCESSO_TITULACAO_ANALISE_CURRICULO_FINALIZADA";
        public static readonly string PROCESSO_TITULACAO_ANALISE_CURRICULO_PENDENCIA =  "PROCESSO_TITULACAO_ANALISE_CURRICULO_PENDENCIA";
        public static readonly string PROCESSO_TITULACAO_COMPROVANTE_CURRICULO =  "PROCESSO_TITULACAO_COMPROVANTE_CURRICULO";
        public static readonly string PROCESSO_TITULACAO_APROVACAO =  "PROCESSO_TITULACAO_APROVACAO";
        public static readonly string PROCESSO_TITULACAO_REPROVACAO =  "PROCESSO_TITULACAO_REPROVACAO"; 
                
        public static readonly string EVENTO_NOVA_INSCRICAO = "EVENTO_NOVA_INSCRICAO";
        public static readonly string EVENTO_LIBERACAO_INSCRICAO = "EVENTO_LIBERACAO_INSCRICAO";
        public static readonly string EVENTO_CONFIRMACAO_PAGAMENTO = "EVENTO_CONFIRMACAO_PAGAMENTO";
        public static readonly string EVENTO_ISENCAO_INSCRICAO = "EVENTO_ISENCAO_INSCRICAO";
        public static readonly string EVENTO_CONVITE_PALESTRANTE = "EVENTO_CONVITE_PALESTRANTE";
        public static readonly string EVENTO_PREENCHIMENTO_INSCRICAO = "EVENTO_PREENCHIMENTO_INSCRICAO";
        public static readonly string EVENTO_ENVIO_SENHA =  "EVENTO_ENVIO_SENHA";
        
        public static readonly string PROCESSO_AVALIACAO_CONVITE_AVALIADOR = "PROCESSO_AVALIACAO_CONVITE_AVALIADOR";
        public static readonly string PROCESSO_AVALIACAO_NOVA_INSCRICAO = "PROCESSO_AVALIACAO_NOVA_INSCRICAO";
        public static readonly string PROCESSO_AVALIACAO_CONFIRMACAO_PAGAMENTO = "PROCESSO_AVALIACAO_CONFIRMACAO_PAGAMENTO";
        public static readonly string PROCESSO_AVALIACAO_COBRANCA = "PROCESSO_AVALIACAO_COBRANCA";
        public static readonly string PROCESSO_AVALIACAO_DOCUMENTO_APROVACAO = "PROCESSO_AVALIACAO_DOCUMENTO_APROVACAO";
        public static readonly string PROCESSO_AVALIACAO_DOCUMENTO_PENDENCIA = "PROCESSO_AVALIACAO_DOCUMENTO_PENDENCIA";
        public static readonly string PROCESSO_AVALIACAO_DOCUMENTO_REPROVACAO = "PROCESSO_AVALIACAO_DOCUMENTO_REPROVACAO";
        public static readonly string PROCESSO_AVALIACAO_ANALISE_CURRICULO = "PROCESSO_AVALIACAO_ANALISE_CURRICULO";
        public static readonly string PROCESSO_AVALIACAO_ENVIO_DOCUMENTOS = "PROCESSO_AVALIACAO_ENVIO_DOCUMENTOS";
        public static readonly string PROCESSO_AVALIACAO_ANALISE_INSCRICAO = "PROCESSO_AVALIACAO_ANALISE_INSCRICAO";
        public static readonly string PROCESSO_AVALIACAO_ANALISE_CURRICULO_FINALIZADA =  "PROCESSO_AVALIACAO_ANALISE_CURRICULO_FINALIZADA";
        public static readonly string PROCESSO_AVALIACAO_ANALISE_CURRICULO_PENDENCIA =  "PROCESSO_AVALIACAO_ANALISE_CURRICULO_PENDENCIA";
        public static readonly string PROCESSO_AVALIACAO_INSCRICAO_DESCLASSIFICADA =  "PROCESSO_AVALIACAO_INSCRICAO_DESCLASSIFICADA";
        public static readonly string PROCESSO_AVALIACAO_ETAPA_CONCLUIDA =  "PROCESSO_AVALIACAO_ETAPA_CONCLUIDA";
        public static readonly string PROCESSO_AVALIACAO_ENVIO_SENHA =  "PROCESSO_AVALIACAO_ENVIO_SENHA";
        public static readonly string PROCESSO_AVALIACAO_ETAPA_APROVADA =  "PROCESSO_AVALIACAO_ETAPA_APROVADA";
        public static readonly string PROCESSO_AVALIACAO_ETAPA_REPROVADA =  "PROCESSO_AVALIACAO_ETAPA_REPROVADA";
        
        public static readonly string ASSOCIADO_LINK_ATUALIZACAO =  "ASSOCIADO_LINK_ATUALIZACAO";
        
        public static readonly string EVENTO_ENVIO_CERTIFICADO =  "EVENTO_ENVIO_CERTIFICADO";
                
        
    }

}
