//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTIL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NotificationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTIL.Resources.NotificationMessages", typeof(NotificationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi cadastrado com sucesso!.
        /// </summary>
        public static string addSuccess {
            get {
                return ResourceManager.GetString("addSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O agendamento foi realizado com sucesso!.
        /// </summary>
        public static string agendamentoOK {
            get {
                return ResourceManager.GetString("agendamentoOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro foi excluído com sucesso.
        /// </summary>
        public static string delete_success {
            get {
                return ResourceManager.GetString("delete_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível salvar as informações, tente novamente ou comunique o suporte técnico..
        /// </summary>
        public static string errorSaveInfo {
            get {
                return ResourceManager.GetString("errorSaveInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo foi salvo com sucesso!.
        /// </summary>
        public static string fileSaveSuccess {
            get {
                return ResourceManager.GetString("fileSaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O registro não pôde ser localizado..
        /// </summary>
        public static string invalid_register_id {
            get {
                return ResourceManager.GetString("invalid_register_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A lista nº {0} foi gerada com sucesso!.
        /// </summary>
        public static string listaSuccess {
            get {
                return ResourceManager.GetString("listaSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuário está bloqueado e não pode acessar o sistema..
        /// </summary>
        public static string login_block_user {
            get {
                return ResourceManager.GetString("login_block_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse usuário não está ativo no sistema..
        /// </summary>
        public static string login_inactive_user {
            get {
                return ResourceManager.GetString("login_inactive_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados de acesso são inválidos..
        /// </summary>
        public static string login_invalid {
            get {
                return ResourceManager.GetString("login_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você não realizou logon ou sua sessão expirou. Por favor, informe suas credenciais..
        /// </summary>
        public static string login_no_login {
            get {
                return ResourceManager.GetString("login_no_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O layout informado não está configurado no sistema..
        /// </summary>
        public static string notConfiguredLayout {
            get {
                return ResourceManager.GetString("notConfiguredLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A {0} não foi localizada!.
        /// </summary>
        public static string notFindItem {
            get {
                return ResourceManager.GetString("notFindItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de Coleta Nº {0} cadastrada com sucesso..
        /// </summary>
        public static string novaColetaCriada {
            get {
                return ResourceManager.GetString("novaColetaCriada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário que você altere sua senha antes de prosseguir..
        /// </summary>
        public static string updatePassword {
            get {
                return ResourceManager.GetString("updatePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os dados foram atualizados com sucesso!.
        /// </summary>
        public static string updateSuccess {
            get {
                return ResourceManager.GetString("updateSuccess", resourceCulture);
            }
        }
    }
}
