//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTIL.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ValidationMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UTIL.Resources.ValidationMessages", typeof(ValidationMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já existe um registro com esse(a) valor..
        /// </summary>
        public static string duplicity {
            get {
                return ResourceManager.GetString("duplicity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse valor deve possui {0} caracter(es)..
        /// </summary>
        public static string exactLength {
            get {
                return ResourceManager.GetString("exactLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP é informado é inválido..
        /// </summary>
        public static string invalidCEP {
            get {
                return ResourceManager.GetString("invalidCEP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CNPJ informado é inválido..
        /// </summary>
        public static string invalidCNPJ {
            get {
                return ResourceManager.GetString("invalidCNPJ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CPF informado é inválido..
        /// </summary>
        public static string invalidCPF {
            get {
                return ResourceManager.GetString("invalidCPF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A data informada não é válida..
        /// </summary>
        public static string invalidDate {
            get {
                return ResourceManager.GetString("invalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O arquivo informado não possui uma extensão esperada {0}..
        /// </summary>
        public static string invalidExtensionFile {
            get {
                return ResourceManager.GetString("invalidExtensionFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse campo deve possuir entre {0} e {1} caracteres..
        /// </summary>
        public static string InvalidLength {
            get {
                return ResourceManager.GetString("InvalidLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail informado é inválido..
        /// </summary>
        public static string invalidMail {
            get {
                return ResourceManager.GetString("invalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário informar as justificativas para a solução adotada!.
        /// </summary>
        public static string invalidObs {
            get {
                return ResourceManager.GetString("invalidObs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Você está tentando agendar para uma data muito longe..
        /// </summary>
        public static string maxDateAgendamento {
            get {
                return ResourceManager.GetString("maxDateAgendamento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deve possuir no máximo {0} caracteres..
        /// </summary>
        public static string maxStringLength {
            get {
                return ResourceManager.GetString("maxStringLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to É necessário um período mínimo de {0} dias úteis para realização da coleta..
        /// </summary>
        public static string minDaysGathering {
            get {
                return ResourceManager.GetString("minDaysGathering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecione ao menos 1 {0}..
        /// </summary>
        public static string minOneSelect {
            get {
                return ResourceManager.GetString("minOneSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esse valor deve ser maior do que {0}..
        /// </summary>
        public static string mustBeGreater {
            get {
                return ResourceManager.GetString("mustBeGreater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha e Confirmação deve ser iguais..
        /// </summary>
        public static string passwordConfirmation {
            get {
                return ResourceManager.GetString("passwordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha atual está incorreta!.
        /// </summary>
        public static string passwordInvalid {
            get {
                return ResourceManager.GetString("passwordInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O campo {0} é obrigatório..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O CEP informado não é atendido no momento..
        /// </summary>
        public static string unsuportedCep {
            get {
                return ResourceManager.GetString("unsuportedCep", resourceCulture);
            }
        }
    }
}
